// <auto-generated />
using System;
using HotelsViewer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelsViewer.Migrations
{
    [DbContext(typeof(HotelsViewerDbContext))]
    [Migration("20180803173901_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelsViewer.Data.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<int?>("ImagesId");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("ImagesId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelsViewer.Data.Entities.HotelImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("HotelImage");
                });

            modelBuilder.Entity("HotelsViewer.Data.Entities.Hotel", b =>
                {
                    b.HasOne("HotelsViewer.Data.Entities.HotelImage", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesId");
                });
#pragma warning restore 612, 618
        }
    }
}
